version: "3.9"
services:
  spring:
    container_name: spring
    image: wns312/coffee-station-backend:latest
    ports:
      - 8080:8080
    networks:
      - runner
    restart: unless-stopped
    env_file:
      - ../../secret/.env
  # redis:
  #   container_name: redis
  #   image: redis:latest
  #   networks:
  #     - runner
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./data:/data
  #   command: redis-server --appendonly yes
networks:
  runner:
