spring:
  profiles:
    include: API-KEY
  #  redis:
#    host: localhost
#    port: 6379

## MYSQL 일 경우에
  datasource:
    url: jdbc:mysql://3.38.99.110:3306/coffee_station
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

### H2 서버일 경우
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    driver-class-name: org.h2.Driver
#    username: sa
#    show-sql: true

  jpa:
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    hibernate:
#      ddl-auto: none
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
    open-in-view: false

#cloud:
#  aws:
#    credentials:
#      accessKey:
#      secretKey:
#    s3:
#      bucket:
#    region:
#      static: us-east-2
#    stack:
#      auto: false

logging.level:
  org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true
jwt:
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa

cloud:
  aws:
    s3:
      bucket: coffee-station
    region:
      static: ap-northeast-2
    stack:
      auto: false