spring:
  profiles:
    include: API-KEY
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/coffeestation
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
    open-in-view: false

logging.level:
  org.hibernate.SQL: DEBUG

decorator:
  datasource:
    p6spy:
      enable-logging: true

jwt:
  secret: ${JWT_SECRET}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_S3_REGION}
    stack:
      auto: false
