spring:
#  redis:
#    host: localhost
#    port: 6379
#  datasource:
#    url: jdbc:mysql://localhost:3306/ssafydb
#    username: root
#    password: ssafy
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

#cloud:
#  aws:
#    credentials:
#      accessKey:
#      secretKey:
#    s3:
#      bucket:
#    region:
#      static: us-east-2
#    stack:
#      auto: false

logging.level:
  org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true
