name: Stage Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: master
    steps:
      - uses: actions/checkout@v2

      - name: Apply env
        env:
          SECRET_PASSPHRASE_LOCAL: ${{ secrets.SECRET_PASSPHRASE_LOCAL }}
          SECRET_PASSPHRASE_PROD: ${{ secrets.SECRET_PASSPHRASE_PROD }}
        run: |
          cd secret
          sh decrypt_secret_prod.sh && set -a && source .env && set +a

      - name: Docker login
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build the Docker image
        run: |
          cd ${{ github.workspace }}/backend/runner
          docker build . --tag wns312/coffee-station-backend:latest

      - name: Push the Docker image
        run: |
          docker push wns312/coffee-station-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    environment: master
    steps:
      - uses: actions/checkout@v2

      - name: Apply env
        env:
          SECRET_PASSPHRASE_LOCAL: ${{ secrets.SECRET_PASSPHRASE_LOCAL }}
          SECRET_PASSPHRASE_PROD: ${{ secrets.SECRET_PASSPHRASE_PROD }}
        run: |
          cd ${{ github.workspace }}/secret
          sh decrypt_secret_prod.sh && set -a && source .env && set +a

      - name: Docker login
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Pull docker images
        run: |
          docker pull wns312/coffee-station-backend:latest

      - name: Docker compose up with prod yml files
        run: |
          cd ${{ github.workspace }}/docker/coffeestation-amd64
          docker-compose -f docker-compose-prod.yml up -d


